# Testing for Empty read

## Setup

### Imports

In [1]:
from typing import Callable, List

import re
import logging
import pprint
from pathlib import Path

#### Packages

In [2]:
import numpy as np
import pandas as pd

#### Local Imports

Handle empty objects of different types.

**Empty Object Examples**
- _None_ will always be considered empty. `None` 
- _Empty String_ `''`
- _Empty List_ `[]`
- _Integer 0_ `0`
- _DataFrame containing no values_ `pd.DataFrame()`
- _Numpy Array containing all NaN_ `np.full((2, 3), np.nan, dtype=float)`
- _DataFrame containing all NaN_ `pd.DataFrame(index=range(3), columns=range(2))`

In [20]:
empty_read_itm_possibilities = [
    None,
    '',
    [],
    pd.DataFrame(),
    np.empty((2, 3), dtype=float),
    pd.DataFrame(index=range(3), columns=range(2))
    ]


In [21]:
for itm in empty_read_itm_possibilities:
    print(itm)

None

[]
Empty DataFrame
Columns: []
Index: []
[[0. 0. 0.]
 [0. 0. 0.]]
     0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN


In [44]:
for itm in empty_read_itm_possibilities:
    try:
        has_value = bool(itm)
    except ValueError as err:
        print(f'{str(err.__class__)} raised by\n {repr(itm)}')
    else:
        print(f'{repr(itm)} is {str(has_value)}')

None is False
'' is False
[] is False
<class 'ValueError'> raised by
 Empty DataFrame
Columns: []
Index: []
<class 'ValueError'> raised by
 array([[0., 0., 0.],
       [0., 0., 0.]])
<class 'ValueError'> raised by
      0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN


In [46]:
for itm in empty_read_itm_possibilities:
    try:
        has_value = bool(itm)
    except ValueError as err:
        print(f'{str(err.__class__)} raised by\n\t{repr(itm)}\n')
        has_empty_attribute = hasattr(itm,'empty')
        if has_empty_attribute:
            print(f'Is {repr(itm)} empty: {str(itm.empty)}')
        else:
            print(f'{repr(itm)}\n does not have an "empty" attribute.\n')
            np.isnan(itm).all()
            has_isna_attribute = hasattr(itm,'isna')
            if has_isna_attribute:
                print(f'Is {repr(itm)} empty: {str(itm.isna())}')
            else:
                print(f'{repr(itm)}\n does not have an "isna" attribute.\n')
    else:
        print(f'{repr(itm)} is {str(has_value)}')

None is False
'' is False
[] is False
<class 'ValueError'> raised by
	Empty DataFrame
Columns: []
Index: []

Is Empty DataFrame
Columns: []
Index: [] empty: True
<class 'ValueError'> raised by
	array([[0., 0., 0.],
       [0., 0., 0.]])

array([[0., 0., 0.],
       [0., 0., 0.]])
 does not have an "empty" attribute.

array([[0., 0., 0.],
       [0., 0., 0.]])
 does not have an "isna" attribute.

<class 'ValueError'> raised by
	     0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN

Is      0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN empty: False


In [18]:
print(np.full((2, 3), np.nan, dtype=float))

[[nan nan nan]
 [nan nan nan]]


In [16]:
pd.DataFrame(index=range(3), columns=range(2))

0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN

In [3]:
a = np.full((2, 3), np.nan, dtype=float)
a

array([[nan, nan, nan],
       [nan, nan, nan]])

In [4]:
np.isnan(a)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [5]:
np.isnan(a).all()

True

In [6]:
a = np.full((2, 3), np.nan, dtype=float)
a[1,2] = 1
a

array([[nan, nan, nan],
       [nan, nan,  1.]])

In [7]:
np.isnan(a)

array([[ True,  True,  True],
       [ True,  True, False]])

In [8]:
np.isnan(a).all()

False

In [9]:
a = pd.DataFrame(index=range(3), columns=range(2))
a


0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN

In [10]:
a.empty

False

SyntaxError: invalid syntax (Temp/ipykernel_20992/445316355.py, line 5)

In [ ]:
non_empty_read_itm_possibilities = [
    'a',
    [0],
    0,
    



#### DVH

In [ ]:
dvh = pd.DataFrame({
    'Course': ['PLAN SUM', 'PLAN SUM', 'PLAN SUM', 'PLAN SUM'],
    'Plan': ['Plan Sum', 'Plan Sum', 'Plan Sum', 'Plan Sum'],
    'Structure': ['PRV5 SpinalCanal', 'PRV5 SpinalCanal',
                    'PTV 50', 'PTV 50'],
    'Data': ['Dose [cGy]', 'Ratio of Total Structure Volume [%]',
                'Dose [cGy]', 'Ratio of Total Structure Volume [%]'],
    0: [0, 100, 0, 100],
    1: [1, 100, 1, 100],
    2: [2, 100, 2, 100],
    3: [3, 100, 3, 100],
    4: [4, 100, 4, 100],
    5: [5, 100, 5, 100],
    6: [3667, 4.23876e-005, 5437, 9.4777e-005],
    7: [3668, 2.87336e-005, 5438, 6.35607e-005],
    8: [3669, 1.50797e-005, 5439, 3.62425e-005],
    9: [3670, 1.4257e-006, 5440, 1.82336e-005],
    10: [np.nan, np.nan, 5441, 9.15003e-006],
    11: [np.nan, np.nan, 5442, 6.6481e-008]
    })
dvh.set_index(['Course', 'Plan', 'Structure', 'Data'],
                inplace=True)
dvh = dvh.T
dvh

Course            PLAN SUM                                                 \
Plan              Plan Sum                                                  
Structure PRV5 SpinalCanal                                         PTV 50   
Data            Dose [cGy] Ratio of Total Structure Volume [%] Dose [cGy]   
0                      0.0                          100.000000        0.0   
1                      1.0                          100.000000        1.0   
2                      2.0                          100.000000        2.0   
3                      3.0                          100.000000        3.0   
4                      4.0                          100.000000        4.0   
5                      5.0                          100.000000        5.0   
6                   3667.0                            0.000042     5437.0   
7                   3668.0                            0.000029     5438.0   
8                   3669.0                            0.000015     5439.0   
9                   3670.0                            0.000001     5440.0   
10                     NaN                                 NaN     5441.0   
11                     NaN                                 NaN     5442.0   

Course                                         
Plan                                           
Structure                                      
Data      Ratio of Total Structure Volume [%]  
0                                1.000000e+02  
1                                1.000000e+02  
2                                1.000000e+02  
3                                1.000000e+02  
4                                1.000000e+02  
5                                1.000000e+02  
6                                9.477700e-05  
7                                6.356070e-05  
8                                3.624250e-05  
9                                1.823360e-05  
10                               9.150030e-06  
11                               6.648100e-08

#### Context

In [ ]:
context = {
    'File Name': 'Test_DVH_Sections.txt',
    'File Path': Path.cwd() / 'Text Files' / 'Test_DVH_Sections.txt',
    'Line Count': 0
    }
context

{'File Name': 'Test_DVH_Sections.txt',
 'File Path': WindowsPath("c:/Users/smoke/OneDrive - Queen's University/Python/Projects/sectionary package/Text Files/Test_DVH_Sections.txt"),
 'Line Count': 0}